
services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dailyreminder
    volumes:
      - postgres-daily-data:/var/lib/postgresql/data

volumes:
  postgres-daily-data: